# Generated by Django 3.1.3 on 2020-11-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_creation', models.DateTimeField()),
                ('filename', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=25, verbose_name='Contract nr')),
                ('status', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250, verbose_name='Beschrijving')),
                ('category', models.CharField(max_length=50, verbose_name='Categorie')),
                ('owner', models.CharField(max_length=25, verbose_name='Eigenaar')),
                ('owner_email', models.CharField(max_length=50, verbose_name='Eigenaar email')),
                ('owner_phone_nr', models.CharField(max_length=20, verbose_name='Eigenaar telnr')),
                ('type', models.CharField(max_length=20)),
                ('last_end_date', models.DateField(verbose_name='Uiterste einddatum')),
                ('interface_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracten', to='rm.interfacecall')),
            ],
        ),
    ]
