# Generated by Django 3.1.3 on 2020-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Beschrijving'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='last_end_date',
            field=models.DateField(null=True, verbose_name='Uiterste einddatum'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner',
            field=models.CharField(blank=True, max_length=25, verbose_name='Eigenaar'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Eigenaar email'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='owner_phone_nr',
            field=models.CharField(blank=True, max_length=20, verbose_name='Eigenaar telnr'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
