# Generated by Django 3.1.3 on 2020-12-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0002_auto_20201201_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='last_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Uiterste einddatum'),
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='filename',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
