# Generated by Django 3.1.3 on 2020-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0005_auto_20201201_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacecall',
            name='type',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
    ]
