# Generated by Django 3.1.3 on 2020-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0007_auto_20201202_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacecall',
            name='message',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
