# Generated by Django 3.1.3 on 2020-12-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0008_interfacecall_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contactpersoon naam'),
        ),
        migrations.AddField(
            model_name='contract',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50, verbose_name='Opzegtermijn'),
        ),
        migrations.AddField(
            model_name='contract',
            name='notice_period_available',
            field=models.CharField(blank=True, max_length=50, verbose_name='Opzegtermijn aanwezig'),
        ),
        migrations.AddField(
            model_name='contract',
            name='original_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Oorsponkelijke einddatum'),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Soort Contract'),
        ),
    ]
