# Generated by Django 3.1.3 on 2020-12-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0009_auto_20201203_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='seq_nr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contactpersoon'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_person_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contactpersoon email'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contactpersoon naam'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contact_person_phone_nr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contactpersoon telnr'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Contract naam'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_nr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contracteigenaar'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_owner_email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Contracteigenaar email'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_owner_phone_nr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contracteigenaar telnr'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='database_nr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Beschrijving'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='description_contract',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Beschrijving contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabrikant'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manufacturer_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fabrikant Adres'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manufacturer_kvk_nr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabrikant KvK nr'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='manufacturer_website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabrikant Website'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Opzegtermijn'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notice_period_available',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Opzegtermijn aanwezig'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_level_manager',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_level_manager_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_level_manager_2_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_level_manager_2_phone_nr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_level_manager_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='service_level_manager_phone_nr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Soort Contract'),
        ),
    ]
