# Generated by Django 3.1.3 on 2020-12-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0010_auto_20201207_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveddata',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='receiveddata',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
