# Generated by Django 3.1.3 on 2020-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0011_auto_20201209_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacecall',
            name='system',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
