# Generated by Django 3.1.5 on 2021-01-11 11:54

from django.db import migrations


class Migration(migrations.Migration):
    """
    Once created, but not needed.
    Permissions were added here to contract, but I decided later to add them to InterfaceCall and with another name.
    """
    dependencies = [
        ('rm', '0012_interfacecall_system'),
    ]

    operations = [
    ]
