# Generated by Django 3.1.5 on 2021-01-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0013_auto_20210111_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={},
        ),
        migrations.AlterModelOptions(
            name='interfacecall',
            options={'permissions': [('upload_contract_file', 'Can upload file with contracts'), ('call_contract_interface', 'Can call the (negometrix) contract-interface')]},
        ),
    ]
