# Generated by Django 3.1.5 on 2021-01-12 14:09

from django.db import migrations


class Migration(migrations.Migration):
    """
    Once created, but not needed.
    Permissions were removed here, but I did that by removing them from the creation script (same git commit)
    """
    dependencies = [
        ('rm', '0014_auto_20210112_1212'),
    ]

    operations = [
    ]
