# Generated by Django 3.1.5 on 2021-01-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210126_1630'),
        ('rm', '0016_auto_20210113_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Naam')),
                ('description', models.CharField(max_length=50, verbose_name='Omschrijving')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Naam')),
                ('description', models.CharField(max_length=50, verbose_name='Omschrijving')),
                ('interface_type', models.CharField(choices=[('API', 'API'), ('UPL', 'Upload')], max_length=3)),
                ('url', models.URLField(blank=True)),
                ('dataset_type_contracten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.datasettype')),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Naam/Code/Sleutel')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizationalunit')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='original_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Oorspronkelijke einddatum'),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Naam')),
                ('description', models.CharField(max_length=50, verbose_name='Omschrijving')),
                ('dataset_types', models.ManyToManyField(through='rm.InterfaceDefinition', to='rm.DataSetType')),
                ('org_units', models.ManyToManyField(through='rm.Mapping', to='users.OrganizationalUnit')),
            ],
        ),
        migrations.AddField(
            model_name='mapping',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.system'),
        ),
        migrations.AddField(
            model_name='interfacedefinition',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.system'),
        ),
        migrations.CreateModel(
            name='DataSetPerOrgUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_data_rows_ok', models.IntegerField(verbose_name='Dataregels goed')),
                ('number_of_data_rows_warning', models.IntegerField(verbose_name='Dataregels waarschuwing')),
                ('interface_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.interfacecall')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizationalunit')),
            ],
        ),
    ]
