# Generated by Django 3.1.5 on 2021-01-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0017_auto_20210126_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasettype',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Omschrijving'),
        ),
        migrations.AlterField(
            model_name='interfacedefinition',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Omschrijving'),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Omschrijving'),
        ),
    ]
