# Generated by Django 3.1.5 on 2021-01-27 11:45

from django.db import migrations, models
import django.db.models.deletion


def delete_contracts_and_interfacecalls(apps, schema_editor):
    """
    Remove Contracts and Interface calls because otherwise we can not add new ForeignKeys to it.
    And since we do not need the data yet we can remove it.
    """
    Contract = apps.get_model("rm", "Contract")
    Contract.objects.all().delete()

    InterfaceCall = apps.get_model("rm", "InterfaceCall")
    InterfaceCall.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0018_auto_20210127_1021'),
    ]

    operations = [
        migrations.RunPython(delete_contracts_and_interfacecalls),
    ]
