# Generated by Django 3.1.5 on 2021-01-27 11:55

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0019_auto_20210127_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceivedData',
            new_name='RawData',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='interface_call',
        ),
        migrations.RemoveField(
            model_name='interfacecall',
            name='system',
        ),
        migrations.AddField(
            model_name='contract',
            name='data_per_org_unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contracten', to='rm.datasetperorgunit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interfacecall',
            name='interface_definition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='interface_calls', to='rm.interfacedefinition'),
            preserve_default=False,
        ),
    ]
