# Generated by Django 3.1.5 on 2021-01-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0020_auto_20210127_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='raw_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rm.rawdata'),
        ),
    ]
