# Generated by Django 3.1.5 on 2021-01-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0021_contract_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfacecall',
            name='type',
        ),
    ]
