# Generated by Django 3.1.5 on 2021-01-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210127_1027'),
        ('rm', '0022_remove_interfacecall_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataSetPerOrgUnit',
            new_name='DataPerOrgUnit',
        ),
    ]
