# Generated by Django 3.1.5 on 2021-01-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0023_auto_20210127_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacecall',
            name='number_of_data_rows_error',
            field=models.IntegerField(default=0, verbose_name='Dataregels fout'),
        ),
        migrations.AddField(
            model_name='interfacecall',
            name='number_of_data_rows_ignored',
            field=models.IntegerField(default=0, verbose_name='Dataregels genegeerd'),
        ),
        migrations.AddField(
            model_name='interfacecall',
            name='number_of_data_rows_ok',
            field=models.IntegerField(default=0, verbose_name='Dataregels goed'),
        ),
        migrations.AddField(
            model_name='interfacecall',
            name='number_of_data_rows_received',
            field=models.IntegerField(default=0, verbose_name='Ontvangen dataregels'),
        ),
        migrations.AddField(
            model_name='interfacecall',
            name='number_of_data_rows_warning',
            field=models.IntegerField(default=0, verbose_name='Dataregels waarschuwing'),
        ),
        migrations.AddField(
            model_name='interfacecall',
            name='number_of_rows_received',
            field=models.IntegerField(default=0, verbose_name='Ontvangen regels'),
        ),
        migrations.AlterField(
            model_name='dataperorgunit',
            name='number_of_data_rows_ok',
            field=models.IntegerField(default=0, verbose_name='Dataregels goed'),
        ),
        migrations.AlterField(
            model_name='dataperorgunit',
            name='number_of_data_rows_warning',
            field=models.IntegerField(default=0, verbose_name='Dataregels waarschuwing'),
        ),
    ]
