# Generated by Django 3.1.5 on 2021-01-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0024_auto_20210127_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='interface_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='rm.interfacecall'),
        ),
    ]
