# Generated by Django 3.1.5 on 2021-01-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0027_auto_20210128_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacecall',
            name='number_of_empty_rows',
            field=models.IntegerField(default=0, verbose_name='Aantal lege regels'),
        ),
        migrations.AddField(
            model_name='interfacecall',
            name='number_of_header_rows',
            field=models.IntegerField(default=0, verbose_name='Aantal header regels'),
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='number_of_data_rows_error',
            field=models.IntegerField(default=0, verbose_name='Aantal dataregels fout'),
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='number_of_data_rows_ignored',
            field=models.IntegerField(default=0, verbose_name='Aantal dataregels genegeerd'),
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='number_of_data_rows_ok',
            field=models.IntegerField(default=0, verbose_name='Aantal dataregels goed'),
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='number_of_data_rows_received',
            field=models.IntegerField(default=0, verbose_name='Aantal ontvangen dataregels'),
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='number_of_data_rows_warning',
            field=models.IntegerField(default=0, verbose_name='Aantal dataregels waarschuwing'),
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='number_of_rows_received',
            field=models.IntegerField(default=0, verbose_name='Aantal ontvangen regels'),
        ),
    ]
