# Generated by Django 3.1.5 on 2021-01-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0028_auto_20210130_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacedefinition',
            old_name='dataset_type',
            new_name='data_set_type',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='dataset_types',
            new_name='data_set_types',
        ),
    ]
