# Generated by Django 3.1.5 on 2021-01-30 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rm', '0029_auto_20210130_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacecall',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interfacecall',
            name='user_email',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interfacecall',
            name='username',
            field=models.CharField(default='onbekend', max_length=250),
            preserve_default=False,
        ),
    ]
