# Generated by Django 3.1.5 on 2021-01-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0030_auto_20210130_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecall',
            name='user_email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='username',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
