# Generated by Django 3.1.5 on 2021-01-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0031_auto_20210130_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataperorgunit',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Actief'),
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='status',
            field=models.CharField(choices=[('API', 'NEW'), ('UPL', 'LOADING'), ('ERROR', 'ERROR'), ('READY_LOADING', 'READY_LOADING'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=15),
        ),
    ]
