# Generated by Django 3.1.5 on 2021-01-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0032_auto_20210131_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='data_per_org_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.dataperorgunit'),
        ),
    ]
