# Generated by Django 3.1.5 on 2021-01-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0033_auto_20210131_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecall',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('LOADING', 'LOADING'), ('ERROR', 'ERROR'), ('READY_LOADING', 'READY_LOADING'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=15),
        ),
    ]
