# Generated by Django 3.1.5 on 2021-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0035_auto_20210202_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacecall',
            name='date_time_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
