# Generated by Django 3.1.5 on 2021-02-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0036_auto_20210202_1002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contract',
            new_name='StageContract',
        ),
    ]
