# Generated by Django 3.1.5 on 2021-02-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0037_auto_20210202_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StageContract',
        ),
    ]
