# Generated by Django 3.1.5 on 2021-02-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210127_1027'),
        ('rm', '0038_delete_stagecontract'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataperorgunit',
            unique_together={('interface_call', 'org_unit')},
        ),
    ]
