# Generated by Django 3.1.5 on 2021-02-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0039_auto_20210203_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfacecall',
            options={'permissions': [('contracten_api', 'Contracten API'), ('contracten_upload', 'Contracten upload'), ('upload_contract_file', 'Can upload file with contracts'), ('call_contract_interface', 'Can call the (negometrix) contract-interface')]},
        ),
    ]
