# Generated by Django 3.1.5 on 2021-02-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0040_auto_20210207_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfacecall',
            options={'permissions': [('contracten_api', 'Contracten API'), ('contracten_upload', 'Contracten upload')]},
        ),
    ]
