# Generated by Django 3.1.5 on 2021-02-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0041_auto_20210207_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfacecall',
            options={'permissions': [('contracten_api', 'Contracten API'), ('contracten_upload', 'Contracten upload'), ('contracten_view', 'Contracten view')]},
        ),
        migrations.AlterField(
            model_name='interfacecall',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('LOADING', 'LOADING'), ('ERROR', 'ERROR'), ('OK', 'OK'), ('READY_LOADING', 'READY_LOADING'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=15),
        ),
    ]
