# Generated by Django 3.1.5 on 2021-02-15 09:27

from django.db import migrations


def create_negometrix_statics(apps, schema_editor):
    System = apps.get_model('rm.System')
    DataSetType = apps.get_model('rm.DataSetType')
    InterfaceDefinition = apps.get_model('rm.InterfaceDefinition')

    new_system, created = System.objects.get_or_create(name="Negometrix")
    new_datasettype, created = DataSetType.objects.get_or_create(name= "Contracten")
    new_int_def, created = InterfaceDefinition.objects.get_or_create(name= "Contracten upload",
                                                                     system=new_system,
                                                                     data_set_type=new_datasettype)


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0042_auto_20210215_1023'),
    ]

    operations = [
        migrations.RunPython(create_negometrix_statics),
    ]
