# Generated by Django 3.1.5 on 2021-01-13 08:56

from django.db import migrations

"""
Empty migration, created but not needed. Too much hassle to remove, once created. 
"""

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
