# Generated by Django 3.1.5 on 2021-01-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210113_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naam')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naam')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='name_in_negometrix',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Naam in Negrometrix'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naam')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cluster')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='clusters',
            field=models.ManyToManyField(to='users.Cluster'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(to='users.Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teams',
            field=models.ManyToManyField(to='users.Team'),
        ),
    ]
