# Generated by Django 3.1.5 on 2021-01-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210115_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name_in_negometrix',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Naam in Negometrix'),
        ),
    ]
