# Generated by Django 3.1.5 on 2021-01-25 07:52

from django.db import migrations

def create_tech_organization(apps, schema_editor):
    """
    First delete all existing Departments, Clustes and Teams
    Then insert the organization structure of the Technologie department of NPO
    """
    Department = apps.get_model("users", "Department")
    Cluster = apps.get_model("users", "Cluster")
    Team = apps.get_model("users", "Team")

    Team.objects.all().delete()
    Cluster.objects.all().delete()
    Department.objects.all().delete()

    # DEPARTMENT TECHNOLOGIE

    dep_tech = Department.objects.create(name="Technologie", cost_centre="781100")

    # CLUSTER FRONT-END

    cluster_front_end = Cluster.objects.create(name="Tech Cluster Front-end Services",
                                               cost_centre="781200",
                                               department=dep_tech)

    team_782150 = Team.objects.create(name="PT: NPO Start & Players",
                                      cost_centre="782150",
                                      cluster=cluster_front_end)

    team_782180 = Team.objects.create(name="PT: Sites & Apps",
                                      cost_centre="782180",
                                      cluster=cluster_front_end)

    team_782190 = Team.objects.create(name="PT: NPO Start Scale Up",
                                      cost_centre="782190",
                                      cluster=cluster_front_end)

    # CLUSTER MEDIA TECHNIEK

    cluster_media_tec = Cluster.objects.create(name="Tech Cluster Media Techniek",
                                               cost_centre="781300",
                                               department=dep_tech)

    team_782160 = Team.objects.create(name="PT: Publicatie Audio",
                                      cost_centre="782160",
                                      cluster=cluster_media_tec)

    team_782170 = Team.objects.create(name="PT: Publicatie Video",
                                      cost_centre="782170",
                                      cluster=cluster_media_tec)

    # CLUSTER BACK-END SERVICES

    cluster_back_end  = Cluster.objects.create(name="Tech Cluster Back-end Services",
                                               cost_centre="781400",
                                               department=dep_tech)

    team_782100 = Team.objects.create(name="PT: End-User Services",
                                      cost_centre="782100",
                                      cluster=cluster_back_end)

    team_782110 = Team.objects.create(name="PT: Hosting & Streaming",
                                      cost_centre="782110",
                                      cluster=cluster_back_end)

    team_782120 = Team.objects.create(name="PT: IaaS",
                                      cost_centre="782120",
                                      cluster=cluster_back_end)

    team_782200 = Team.objects.create(name="PT: Data Services",
                                      cost_centre="782200",
                                      cluster=cluster_back_end)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210125_0738'),
    ]

    operations = [
        migrations.RunPython(create_tech_organization),
    ]
