# Generated by Django 3.1.5 on 2021-01-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_insert_dep_clus_team_for_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Naam')),
                ('type', models.CharField(choices=[('AFD', 'Afdeling'), ('CLU', 'Cluster'), ('TEA', 'Team')], max_length=3)),
                ('parent_org_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_org_units', to='users.organizationalunit')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='org_units',
            field=models.ManyToManyField(to='users.OrganizationalUnit'),
        ),
    ]
