# Generated by Django 3.1.5 on 2021-01-26 13:14

from django.db import migrations

def migrate_tech_organization(apps, schema_editor):
    """
    Copy the data from Department, Cluster and Team into
    OrganizationalUnit, including relations between them.

    Also copy the relations from these Departments, Cluster and Team with
    CustomUser to the newly created OrganizationalUnits

    When this is done, we can delete the models (and tables) of Department,
    Cluster and Team views in the next migration.
    """

    Department = apps.get_model("users", "Department")
    Cluster = apps.get_model("users", "Cluster")
    Team = apps.get_model("users", "Team")

    OrganizationalUnit = apps.get_model("users", "OrganizationalUnit")

    # just to be sure, remove all OrganizationUnits
    OrganizationalUnit.objects.all().delete()
    for department in Department.objects.all():
        org_dep = OrganizationalUnit.objects.create(name=department.name,
                                                    type=OrganizationalUnit.AFDELING)
        for user in department.customuser_set.all():
            user.org_units.add(org_dep)
        for cluster in department.cluster_set.all():
            org_clu = OrganizationalUnit.objects.create(name=cluster.name,
                                                        type=OrganizationalUnit.CLUSTER,
                                                        parent_org_unit=org_dep)
            for user in cluster.customuser_set.all():
                user.org_units.add(org_clu)
            for team in cluster.team_set.all():
                org_tea = OrganizationalUnit.objects.create(name=team.name,
                                                            type=OrganizationalUnit.TEAM,
                                                            parent_org_unit=org_clu)
                for user in team.customuser_set.all():
                    user.org_units.add(org_tea)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210126_1234'),
    ]

    operations = [
        migrations.RunPython(migrate_tech_organization),
    ]
