# Generated by Django 3.1.5 on 2021-01-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_migrate_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalunit',
            name='parent_org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_org_units', to='users.organizationalunit'),
        ),
    ]
