# Generated by Django 3.1.5 on 2021-01-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210126_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='clusters',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='teams',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
