# Generated by Django 3.1.5 on 2021-02-18 17:45

from django.db import migrations


def del_permissions_from_buyer_and_cluster_lead(apps, schema_editor):
    Group = apps.get_model('auth.Group')

    _delete_perm(Group, "Buyer", "call_contract_interface")
    _delete_perm(Group, "Buyer", "upload_contract_file")
    _delete_perm(Group, "Buyer", "view_contract")
    _delete_perm(Group, "Cluster Lead", "view_contract")


def _delete_perm(Group, group_name: str, permission_codename: str):
    cluster_lead_group: Group = Group.objects.get(name=group_name)
    old_perms = cluster_lead_group.permissions.filter(codename=permission_codename)
    if len(old_perms) == 0:
        print(f"Permission {permission_codename} was already removed from group {group_name}")
    elif len(old_perms) == 1:
        print(f"Deleting permission {permission_codename} from group {group_name}")
        old_perms[0].delete()
    else:
        print(f"More than 1 permissions in group {group_name} match the filter {permission_codename}:")
        for perm in old_perms:
            print(perm.codename)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_perm_contracte_view_for_clmngr'),
    ]

    operations = [
        migrations.RunPython(del_permissions_from_buyer_and_cluster_lead),
    ]
