# Generated by Django 3.1.5 on 2021-02-03 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rm', '0038_delete_stagecontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_nr', models.IntegerField()),
                ('database_nr', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_nr', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contract_status', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contract naam')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Beschrijving')),
                ('description_contract', models.CharField(blank=True, max_length=250, null=True, verbose_name='Beschrijving contract')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categorie')),
                ('contract_owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contracteigenaar')),
                ('contract_owner_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contracteigenaar email')),
                ('contract_owner_phone_nr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contracteigenaar telnr')),
                ('end_date_contract', models.DateField(blank=True, null=True, verbose_name='Einddatum contract')),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contactpersoon')),
                ('contact_person_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contactpersoon email')),
                ('contact_person_phone_nr', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contactpersoon telnr')),
                ('contact_person_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contactpersoon naam')),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabrikant')),
                ('manufacturer_kvk_nr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabrikant KvK nr')),
                ('manufacturer_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Fabrikant Adres')),
                ('manufacturer_website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabrikant Website')),
                ('contracted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gecontracteerde waarde')),
                ('service_level_manager', models.CharField(blank=True, max_length=50, null=True)),
                ('service_level_manager_email', models.CharField(blank=True, max_length=50, null=True)),
                ('service_level_manager_phone_nr', models.CharField(blank=True, max_length=20, null=True)),
                ('service_level_manager_2', models.CharField(blank=True, max_length=50, null=True)),
                ('service_level_manager_2_email', models.CharField(blank=True, max_length=50, null=True)),
                ('service_level_manager_2_phone_nr', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soort Contract')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('last_end_date', models.DateField(blank=True, null=True, verbose_name='Uiterste einddatum')),
                ('original_end_date', models.DateField(blank=True, null=True, verbose_name='Oorspronkelijke einddatum')),
                ('notice_period', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opzegtermijn')),
                ('notice_period_available', models.CharField(blank=True, max_length=50, null=True, verbose_name='Opzegtermijn aanwezig')),
                ('data_per_org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rm.dataperorgunit')),
            ],
        ),
    ]
